#!/bin/sh

set -e

case "$1" in
    configure)
		update-rc.d tuquitoAjustes start 51 S .
	    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    	;;
    triggered)
	    /usr/lib/tuquito/tuquito-ajustes/tuquito-ajustes.py
    	;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
